### PR TITLE
Dynamic schedule timezones

### PR DESCRIPTION
**Pull request by martey**
- Update database to be more timezone-aware.
  - Add ability for users to change the displayed timezone on schedule pages.

Because this pull request makes significant changes to the database and the design of the schedule pages, it should not be applied to finished conferences.

### CODE REVIEW

**Comment by jasongrout** [comment]
Just curious, does this use the browser timezone information to make an intelligent guess about the right timezone?

I'm excited to see how it handles conference "days" that are now split over two days in a different timezone.

**Comment by jasongrout** [comment]
For example, apparently `Intl.DateTimeFormat().resolvedOptions().timeZone` does a pretty decent job of returning the current timezone - if none is set, perhaps it can be the default rather than the conference timezone?

**Comment by martey** [comment]
FYI: This isn't deployed on the JupyterCon site because I have found an issue with converting existing schedules that I am currently troubleshooting.

> Just curious, does this use the browser timezone information to make an intelligent guess about the right timezone?

No, this uses the conference server's time zone as the default. Since the user-selected time zone is stored in the session, though, conference attendees should not have re-select their preferred time zone each time they visit the site.

> I'm excited to see how it handles conference "days" that are now split over two days in a different timezone.

This pull request does not explicitly deal with that. While choosing a different time zone will show you the local date and time that a presentation is happening on the schedule, it will not change the schedule day that the presentation is associated with.

**Comment by jasongrout** [comment]
> This pull request does not explicitly deal with that. While choosing a different time zone will show you the local date and time that a presentation is happening on the schedule, it will not change the schedule day that the presentation is associated with.

That sounds fine - the conference still has "days", but the time on the left in the schedule shows you the local time (including day)?

**Comment by martey** [comment]
Yes - see https://pydata.org/eindhoven2020/schedule/.

**Pull request merged**
