### PR TITLE
Add list of "assigned" proposals.

### PR DESCRIPTION
**Pull request by martey**
Add new proposal list view containing the list of non-cancelled proposals where the user's review is requested (i.e. a ProposalVote from the user exists with a blank score).

### CODE REVIEW

**Comment by jasongrout** [comment]
This view also has the existing reviews the user has done, not just the proposals with requested reviews, right?

**Comment by jasongrout** [comment]
(i.e., does it list all non-cancelled proposals with a ProposalVote for the user?)

**Comment by martey** [comment]
No, but that is the next thing I am working on, so it should be ready in the next few minutes.

**Comment by jasongrout** [comment]
Cool, thanks

**Comment by jasongrout** [comment]
> No, but that is the next thing I am working on, so it should be ready in the next few minutes.

Just checking, in the same view? I think it would be confusing to have two views, one for proposals I've already reviewed, and one for proposals I haven't yet reviewed, especially when I can sort to easily distinguish the two categories.

**Comment by martey** [comment]
My plan was to put it in a separate view, but I can add the "already reviewed" proposals into this "assigned" proposal list if you want - it's only a one line change, so it is easier.

**Comment by jasongrout** [comment]
> My plan was to put it in a separate view, but I can add the "already reviewed" proposals into this "assigned" proposal list if you want - it's only a one line change, so it is easier.

Yes, please. The point is that there is one place to go to review and *update* reviews, not two different pages depending on what you did last time.

**Comment by martey** [comment]
Okay, both kind of proposals now appear in the same view.

**Pull request merged**
