### PR TITLE
Add __unicode__ methods to allow proper representation

### LINKED ISSUE #24: 'TalkProposal Object' listed in Admin
This needs to have a title instead of listing the object type.

### PR DESCRIPTION
**Pull request by tswicegood**
This fixes #24. cc @brittainhard

### CODE REVIEW

**Comment by codersquid** [comment]
In #34 I added __str__ instead with the python_2_unicode_compatible decorator.

**Comment by tswicegood** [comment]
@codersquid I'm not familiar with Django's `python_2_unicode_compatible` decorator.  Is there a reason to use it over simply defining `__unicode__` as [Django still advocates][1] using `__unicode__` as the default and allowing `__str__` to call for compatibility.

[1]: https://docs.djangoproject.com/en/1.7/ref/unicode/#choosing-between-str-and-unicode

**Comment by codersquid** [comment]
I read [this section[(https://docs.djangoproject.com/en/1.7/topics/python3/#str-and-unicode-methods) of the Django docs on porting to python 3 and chose my approached based on that.

You can reopen if you like.

**Comment by tswicegood** [comment]
Cool -- guess I'm just showing my age... "I remember when we didn't have no fancy decorators and had to walk uphill both ways in the snow to get our `__unicode__` functions working." :-)

**Pull request closed without merging**
