### PR TITLE
Added API to list speaker profiles

### PR DESCRIPTION
**Pull request by narayanaditya95**
@aterrel @martey @gvwilson

This PR allows an admin user to access the list of speaker profiles at the API endpoint.
This would allow AMY to populate its `Person` table with speaker profiles fetched from individual conference site.

### CODE REVIEW

**Comment by gvwilson** [comment]
:+1: from me - what's the corresponding change in AMY?

**Comment by narayanaditya95** [comment]
@gvwilson I haven't pushed that yet.
It will closely resemble the import event machinery.

**Comment by narayanaditya95** [comment]
@gvwilson Addressed the issue you raised at #116.
Will rebase #116 now.

**Comment by martey** [comment]
I think it would make more sense **not** to divide the name field into `get_personal` and `get_family`, since symposion (and by extension, conf_site) uses a unitary name field.

I realize that there might be good reasons why AMY uses three different fields for names (see https://github.com/swcarpentry/amy/issues/61 and https://github.com/swcarpentry/amy/issues/500), but I think any separation of name fields should exist in the AMY import code, not the symposion API.

**Comment by narayanaditya95** [comment]
@martey Yes, it does seem to be an anti-pattern. I will rewrite the logic again at AMY, while the API here would closely resemble the `Speaker` model.

Also, I would like to add another field `role` here that would tell AMY what role each Speaker play during the conference. Did they instruct/help? Can you enumerate the roles that can be applied to each `Speaker` and `User` instance.

**Comment by narayanaditya95** [comment]
@martey I reverted the commit. Are there any further concerns?

**Pull request merged**
