### PR TITLE
Jupytercon

### PR DESCRIPTION
**Pull request by maartenbreddels**
This includes #472 (I guess I can rebase after that is merged?)

I tried not to touch the html, to make rebasing/merging easier, but hide css using `display: none`. We furthermore override the theming in jupytercon.css and use the same vue components from https://github.com/jupytercon/jupytercon2020-website.
Before we merge this we'd like to get those vue components from the master.jupytercon.com server instead, so we can remove it from this branch.

In general, the styling is very similar to the jupytercon website, but it may need some tweaks :

image

### CODE REVIEW

**Comment by maartenbreddels** [comment]
All this needs it a configuration for `jupytercon_base_url`, I'm not sure how to add this, but I think we could test this.

**Comment by mariobuikhuizen** [comment]
From now on https://master.jupytercon.com/ can be used for the exported menu and footer in (27832f8)

**Comment by SylvainCorlay** [comment]
@maartenbreddels can you use the APEX domain now?

**Comment by SylvainCorlay** [comment]
Hey @martey! How does this look to you?

Can we get this in?

**Comment by SylvainCorlay** [comment]
cc @jasongrout

**Pull request merged**
